
$(OBJ_DIR)/pgm.o: $(PGM_DIR)/pgm.c
	$(CC) -c $(CPPFLAGS) $(CFLAGS) $< -o $@

$(OBJ_DIR)/conversion.o: $(SRC_DIR)/conversion.c
	$(CC) -c $(CPPFLAGS) $(CFLAGS) $< -o $@

$(OBJ_DIR)/thresholding.o: $(SRC_DIR)/thresholding.c
	$(CC) -c $(CPPFLAGS) $(CFLAGS) $< -o $@

$(OBJ_DIR)/sobel.o: $(SRC_DIR)/sobel.c
	$(CC) -c $(CPPFLAGS) $(CFLAGS) $< -o $@

$(OBJ_DIR)/threshold_main.o: $(SRC_DIR)/threshold_main.c
	$(CC) -c $(CPPFLAGS) $(CFLAGS) $< -o $@
